### ISSUE TITLE
Permissions always being requested

### ISSUE THREAD

**Issue by gavinharriscolab** [Siclo-Mobile/EZPhotoPicker#11]
I have a function as below:

        private void startCamera() {
            EZPhotoPickConfig config = new EZPhotoPickConfig();

            config.photoSource = PhotoSource.CAMERA;
            config.storageDir = PHOTO_PATH;
            config.needToAddToGallery = true;

            EZPhotoPick.startPhotoPickActivity(this, config);

        }

However each and every time I run this function the Application is requesting Permissions from the user. I cannot see anything in the config that would allow me to ask the PhotoIntentHelperActivity not to ask for permission if permissions have already been granted.

Have I missed something?

**Comment by gavinharriscolab** [comment]
Looking at the code it looks like a simple change to:

PhotoIntentHelperActivity.requestCameraAndExternalStoragePermission() and requestReadExternalStoragePermission()

Something like: 

    @Override
    public void requestCameraAndExternalStoragePermission(boolean needToAddToGallery) {
        String[] permissions;
        if (needToAddToGallery) {
            permissions = new String[]{Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE};
        } else {
            permissions = new String[]{Manifest.permission.CAMERA};
        }

        if(checkPermissions(permissions)) {
			presenter.onRequestCameraPermissionGranted();
		} else {
        	ActivityCompat.requestPermissions(PhotoIntentHelperActivity.this,
                	permissions,
                	REQUEST_CAMERA_PERMISSION);
		}
        
    }
	
    @Override
    public void requestReadExternalStoragePermission() {
	
		if(checkPermissions(permissions)) {
        	presenter.onRequestReadExternalPermissionGranted();
		} else {
	        ActivityCompat.requestPermissions(PhotoIntentHelperActivity.this,
    				new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},
                	REQUEST_READ_EXTERNAL_STORAGE_PERMISSION);
		}
    }
	
    /**
     * checkPermissions: Used as a wrapper over ActivityCompat.checkSelfPermission to validate if a 
     * number of Permissions have been granted
     * @param permissions: The requested Permissions.
     * @return True is all permissions have been graned, otherwise false.
     */
    private boolean checkPermissions(String[] permissions) {

        for(String permission: permissions) {

            if(ActivityCompat.checkSelfPermission(PhotoIntentHelperActivity.this, permission) != PackageManager.PERMISSION_GRANTED) {

                return false;

            }

        }

        return true;

    }

**Comment by ericta** [comment]
thanks @gavinharriscolab , merged, sorry for delaying !
