### ISSUE TITLE
Camera permission requested when Gallery is only one being used

### ISSUE THREAD

**Issue by benzabill** [Siclo-Mobile/EZPhotoPicker#15]
Adding photo picker library added camera permission when I don't think it should be adding it.

Maybe I'm misunderstanding permissions - but shouldn't READ_EXTERNAL_STORAGE permission be sufficient if we're just using "Gallery" for photo source?

**Comment by ericta** [comment]
Hi @benzabill , the READ_EXTERNAL_STORAGE is only requested when you try to pick an uri which is located from external storage. otherwise it wont!
