### ISSUE TITLE
Start camera if external storage permission is granted

### ISSUE THREAD

**Issue by lbenini** [Siclo-Mobile/EZPhotoPicker#16]
Starting the Photopick activity with 
`config.photoSource = PhotoSource.GALLERY`
Show the picture selection (good), but after the image is selected instead of returning to the calling activity the camera is started (!!)
I've isolated the problem in the `requestReadExternalStoragePermission`: if the check is true `onRequestCameraPermissionGranted` in invoked, instead should be `onRequestReadExternalPermissionGranted`

**Comment by ericta** [comment]
hi, thanks @lbenini, it 's my bad, fixed!
