### ISSUE TITLE
Can´t select multiple images from Gallery

### ISSUE THREAD

**Issue by javiersamaniego** [Siclo-Mobile/EZPhotoPicker#17]
Hi! Excellent library but I have a problem. I can't select multiple images from gallery on Android 7.0+ :C.
and EXPhotoPicker only support for InternalStorage? or algo External?

**Comment by ericta** [comment]
hi @javiersamaniego ,
about multiple select: It only work with API > 18
about storage support: yes, only for internal storage. You must copy it to external storage if you want! I will try to support it later
thanks
