### ISSUE TITLE
Oreo

### ISSUE THREAD

**Issue by gkhristian** [Siclo-Mobile/EZPhotoPicker#19]
Hello,

I am having this issue on the Devices that are using Android Oreo:

java.lang.RuntimeException: Unable to start activity ComponentInfo{yenga.app/siclo.com.ezphotopicker.ui.PhotoIntentHelperActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation

Thanks

**Comment by GeoZac** [comment]
On API 26+ devices calling ```startService()``` will raise a **IllegalStateException**,use ```startForegroundService()``` instead, but there is limitation on the waiting period.read more at [Developer guides](https://developer.android.com/about/versions/oreo/background-location-limits.html)

**Comment by ericta** [comment]
hi @gkhristian , I dont think I can get what you re meaning. Can you post your code, please? thanks!

**Comment by Anoimar** [comment]
This happens when your app is targeting api 27 and you use setOrientation in activity.
https://issuetracker.google.com/issues/68454482

**Comment by gkhristian** [comment]
Hello @GeoZac,
Sorry for not anwser before. What @Anoimar says is exactly the issue that I have reproduced in some devices (Xiaomi A1 for ex). I would say that this problem is only happening on Oreo 8.0.X. I have a Pixel XL 2 with 8.1.0 and no issues at all.

Let's see if that's fix on the new Oreo version on A1.

I don't know if something can be added to the EZPhotoPicker to avoid that, maybe not forcing the orientantion or a try catch for this exception...

[(https://stackoverflow.com/questions/46992843/interstitial-admob-ads-illegalstateexception-only-fullscreen-activities-can-r/46995624#46995624)]

Thanks.

**Comment by ravindu1024** [comment]
I got the same issue. You can do this workaround: force`siclo.com.ezphotopicker.ui.PhotoIntentHelperActivity` to a fullscreen theme by using tools:replace in the manifest.

**Comment by FaramarzZ** [comment]
this error shows it self on Api28 and emulator too

**Comment by khanhsiclo** [comment]
This issue has been fixed on version 1.0.10
