### ISSUE TITLE
Get absolute path from latest stored photo

### ISSUE THREAD

**Issue by FranciscoNin** [Siclo-Mobile/EZPhotoPicker#20]
Can we see this feature in a near future? I would love to be able to get the absolute path without the need to pass the file dir and name as a parameter, just as I get when I need the Bitmap.

Thanks!

**Comment by ericta** [comment]
hi @FranciscoNin F
I am working on it, will ping you later, when it is done!

**Comment by ericta** [comment]
hi @FranciscoNin ,
use: 
compile 'com.siclo.ezphotopick:library:1.0.8'
and method:
ezPhotoPickStorage.getLatestStoredPhotoBitmapAbsolutePath()
ezPhotoPickStorage.getLatestStoredPhotoBitmapThumbnailAbsolutePath()

cheer!
