### ISSUE TITLE
get Uri from selected image

### ISSUE THREAD

**Issue by yoesuv** [Siclo-Mobile/EZPhotoPicker#3]
please add Uri from selected image (from gallery or camera)
this is needed for uploading an image.

anyway, thanks for library

**Comment by ericta** [comment]
hi @yoesuv , I dont understand why we need the Uri for uploading the image?
just use the function  from EZPhotoPickStorage class:
`loadStoredPhotoBitmap(String storedPhotoDir, String storedPhotoName) `
to load the target bitmap or function 
`loadLatestStoredPhotoBitmap()`
to load lastest stored bitmap
Then convert it to bytes, and upload it
---------------
In case you still want to Uri, you can do it yourself by this way
the library just stored the photo in your app internal storage, then you just generate the Uri from where you asked the library to store your photo, for eg:
`file = new File(context.getFilesDir().getAbsolutePath() + "/" + yourDirIfYouAdded+"/"yourPhotoName);
  Uri i = Uri.fromFile()`
If you didnt define the photo name when you called the library
the photo name will be: 
`yourPhotoName = loadLatestStoredPhotoName()`

**Comment by yoesuv** [comment]
thanks for quick reply, 
of course, now i already created a method to convert bitmap to Uri,
which is convert all bitmap to .jpg files in my case, then creating a File to get Uri.

now i can close this issue
