### ISSUE TITLE
Could not GET 'https://dl.bintray.com/siclo/SicloAndroidOSS/com/siclo/ezphotopick/library/1.0.10/library-1.0.10.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by MuhammadSufyanMalik** [Siclo-Mobile/EZPhotoPicker#31]
Could not GET 'https://dl.bintray.com/siclo/SicloAndroidOSS/com/siclo/ezphotopick/library/1.0.10/library-1.0.10.pom'. Received status code 403 from server: Forbidden.

I received a project from the client and tried to run it, but it failed.
Gives forbidden error.
Any help would be appreciated.

Thanks

**Comment by Xpjay** [comment]
I have the same problem...
did you find a solution ? 

> Could not GET 'https://dl.bintray.com/siclo/SicloAndroidOSS/com/siclo/ezphotopick/library/1.0.10/library-1.0.10.pom'. Received status code 403 from server: Forbidden.
> 
> I received a project from the client and tried to run it, but it failed.
> Gives forbidden error.
> Any help would be appreciated.
> 
> Thanks

**Comment by MuhammadSufyanMalik** [comment]
I have changed the library.

**Comment by MuhammadSufyanMalik** [comment]
I am closing because didn't receive any support from the creator, at last, I Used another library.
