### ISSUE TITLE
Project sdk is not define

### ISSUE THREAD

**Issue by iam-mrinmoy** [Siclo-Mobile/EZPhotoPicker#4]
after opening the project when moved to MainActivity.java it shows project sdk is not defined (setup sdk)
after setting up the sdk (api 24). it shows below error:

PM Frameworks detected: Android framework is detected in the project Configure

![1](https://cloud.githubusercontent.com/assets/24508742/22396964/3385032c-e58b-11e6-8a76-833af17c530f.png)
![2](https://cloud.githubusercontent.com/assets/24508742/22396966/338571ea-e58b-11e6-89e0-86acad53efab.png)
![3](https://cloud.githubusercontent.com/assets/24508742/22396968/33886ed6-e58b-11e6-9629-26a5af6b74e4.png)
![4](https://cloud.githubusercontent.com/assets/24508742/22396967/33860786-e58b-11e6-8f74-0f140ee0dfb9.png)
![5](https://cloud.githubusercontent.com/assets/24508742/22396965/33854670-e58b-11e6-973e-5fbb2664d79c.png)

please see the matter. 
and please provide any documentation on saving and loading of a image if available.
Thanks

**Comment by ericta** [comment]
hi @iam-mrinmoy , I dont know what happen with your case, but what you need to check here is your gradle file, not manifest....
But for importing library purporse, just please simple add the repository to your gradle file as the guidline
