### ISSUE TITLE
Error:(26, 13) Failed to resolve: com.siclo.ezphotopick:library:1.0.2 

### ISSUE THREAD

**Issue by kamalsint** [Siclo-Mobile/EZPhotoPicker#5]
Hi,

I am trying to include this library via gradle but there occurs an error, unable to find what the problem is. Kindly help me with your suggestions. My gradle file is included below.

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "ezpic.sample.com.ezphotopicsample"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.siclo.ezphotopick:library:1.0.2'
    compile 'com.android.support:appcompat-v7:25.1.1'
    testCompile 'junit:junit:4.12'

}

**Comment by ericta** [comment]
hi @kamalsint 
u re missing
`repositories {
    mavenCentral()
    maven {
        url 'https://dl.bintray.com/siclo/SicloAndroidOSS'
    }
}`

**Comment by kamalsint** [comment]
Hi Ericta,

Thanks for the quick reply. It is working fine now. Very simple and excellent lib. Thanks once again.
