### ISSUE TITLE
Can we select multiple images with this?

### ISSUE THREAD

**Issue by Anu07** [Siclo-Mobile/EZPhotoPicker#7]
Can we select multiple images with this?

**Comment by ericta** [comment]
hi @Anu07 
please use 
```
compile 'com.siclo.ezphotopick:library:1.0.3'
```
and add this config when starting picking photo
```
config.isAllowMultipleSelect = true; 
```
remember this config  only works with 2 conditions
-API >18 
-the picked gallery application must support multiple pick
