### ISSUE TITLE
I want  to get the path , URI and Size of Image in the List in case of Multiselect....

### ISSUE THREAD

**Issue by akshaylamba** [Siclo-Mobile/EZPhotoPicker#8]
I want  to get the path , URI and Size of Image in the List in case of Multiselect....

Below is What i Tried But Did not Succeed ...Pls Guide me

 if (requestCode == EZPhotoPick.PHOTO_PICK_GALERY_REQUEST_CODE || requestCode == EZPhotoPick.PHOTO_PICK_CAMERA_REQUEST_CODE) {

                EZPhotoPickStorage ezPhotoPickStorage=new EZPhotoPickStorage(CHATmainACTIVITY.this);

                ArrayList<String> pickedPhotoNames = data.getStringArrayListExtra(EZPhotoPick.PICKED_PHOTO_NAMES_KEY);

                for(String photoName: pickedPhotoNames){

                    ImageURI=Uri.parse(photoName);

                    File f=new File(ImageURI.getPath());

                    Toast.makeText(this, "File Size >> "+f.length(), Toast.LENGTH_SHORT).show();

                  //  Bitmap pickedPhoto = ezPhotoPickStorage.loadStoredPhotoBitmap(photoDir, photoName, 300);

                }

                Toast.makeText(this, "Size >>"+pickedPhotoNames.size(), Toast.LENGTH_SHORT).show();

                //do something with the bitmap
            }

**Comment by akshaylamba** [comment]
This Issues is Solved...

 String photoDir = "";
                        String photoPath = ezPhotoPickStorage.getAbsolutePathOfStoredPhoto(photoDir, photoName);


                        File f = new File(photoPath);

**Comment by ericta** [comment]
Yes, I already added to the lib, let me know if you need some other things

**Comment by akshaylamba** [comment]
I was Trying to Use Cropping when Single Image is Selected and When
Multiple Image is Selected I Go By Your Workflow...


When using https://github.com/ArthurHub/Android-Image-Cropper library for
Cropping Your Intent Data Return nothing....Pls Check..


after selecting image from the gallery , it Takes Time to Load as a
Progress Dialog is shown...Can We remove that and fasten the Process....

Thanks & Regards,
*Akshay Deep Lamba*  |   *Cosmic *
Phone: +9106542235688  |   Fax: +9106542235010  | Mobile : +919304809841
Email: akshay@cosmicAD.com  |   Site: www.cosmicAD.com
<http://www.cosmicad.com%20%20/>|  Address: Main Road,Chas,
Bokaro,Jharkhand - 827 013, India


*|    BLOG : http://geekswithblogs.net/akshaylamba
<http://geekswithblogs.net/akshaylamba>            | *


*|    Email Your Feedback at  feedback@cosmicad.com
<feedback@cosmicad.com>     |*


*This email and any attachments may contain confidential information. If
you are not the intended recipient and you have received this email in
error, please reply to the sender indicating that fact and delete the copy
you received without printing, copying, retransmitting, disseminating the
information. You should check this email and any attachments for viruses as
COSMIC ADVERTISERS PVT. LTD. accepts no responsibility for any damage
caused by any virus transmitted by this email.*
