### ISSUE TITLE
Cropping and Image Load Up...

### ISSUE THREAD

**Issue by akshaylamba** [Siclo-Mobile/EZPhotoPicker#9]
I was Trying to Use Cropping when Single Image is Selected and When Multiple Image is Selected I Go By Your Workflow...

after selecting image from the gallery , it Takes Time to Load as a Progress Dialog is shown...Can We remove that and fasten the Process....i think reducing the image size before loading and after selecting can help... pls see to it..

Gives  the Below error sometime ....
FATAL EXCEPTION: Thread-27863
                                                                            

>   Process: com.example.cosmic.zumi_test, PID: 11225
>                                                                               java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 16777120 free bytes and 25MB until OOM
>                                                                                   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
>                                                                                   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
>                                                                                   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:667)
>                                                                                   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:643)
>                                                                                   at siclo.com.ezphotopicker.storage.PhotoGenerator.generatePhotoByUriWithMaxSize(PhotoGenerator.java:101)
>                                                                                   at siclo.com.ezphotopicker.storage.PhotoGenerator.generatePhotoWithValue(PhotoGenerator.java:126)
>                                                                                   at siclo.com.ezphotopicker.ui.PhotoIntentHelperPresenter.processPickedUri(PhotoIntentHelperPresenter.java:141)
>                                                                                   at siclo.com.ezphotopicker.ui.PhotoIntentHelperPresenter.access$100(PhotoIntentHelperPresenter.java:35)
>                                                                                   at siclo.com.ezphotopicker.ui.PhotoIntentHelperPresenter$1.run(PhotoIntentHelperPresenter.java:131)
>                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by ericta** [comment]
hi @akshaylamba , there re 1 config named: "exportingSize", it define maximum size of each size and keeping ratio of the photo.
for eg:
exportingSize = 1000;
your photo : W x H : 2000 x 500;
then after picking photo: W x H: 1000 x 250.
sorry for late response!
